### ISSUE TITLE
Negative variance estimate?

### ISSUE THREAD

**Issue by cwliu007** [wbelzak/regDIF#2]
Hello,

Thank you for providing the package for DIF assessment. I got some questions when using the package and wonder if you could give me some directions:

1. Why the variance estimates of impact can be negative? For example, the `var.gender` for `ida` dataset shown at https://cran.r-project.org/web/packages/regDIF/vignettes/regdif_vignette.html. 
I suppose the variance should be constrained positive throughout the penalized EM optimization. 

2. Could you give an example of the R code for providing `start.values`? I tried to given starting values for the `var.gender` but not worked. 

Regards,
CW

**Comment by wbelzak** [comment]
Hi CW,

1. It is not a negative estimate of variance, but rather a negative _effect on_ variance impact. Given that the default in regDIF is for the baseline/reference mean to equal 0 and the baseline/reference variance to equal 1, a negative effect on variance impact would imply that the focal group has a smaller variance than the baseline/reference group. See this [comment](https://github.com/wbelzak/regDIF/issues/3#issuecomment-1357898523) for more details.
2. The `start.values` argument has the same list structure as the output of `coef(fit)`, except that you do not need to provide the tau values. Here's an example where I change the starting values of the baseline intercepts and slopes to 0s and 1s respectively:

`item.data <- ida[,1:6]`
`pred.data <- ida[,7:9]`

`fit      <- regDIF(item.data,pred.data,tau=0,anchor=1:ncol(item.data))`
`coef_fit <- coef(fit)`

`coef_fit$base <- matrix(c(rep(0,6), rep(1,6)))`

`fit_startvals <- regDIF(item.data,pred.data,tau=0,anchor=1:ncol(item.data),control=list(start.values=coef_fit))`

Best,
Will
