### ISSUE TITLE
Comparison of mirt and regDIF

### ISSUE THREAD

**Issue by cwliu007** [wbelzak/regDIF#3]
Hello,

I tried to simulate two-group data without any DIF items (for testing purposes). Male group from `N(0,1)` and female group from `N(1,1)`. 2PLM was used as the generating model. The true `slope` parameters are all one and the `intercept` parameters are all zero. Attached is the simulated data and the R syntax (change test.txt to test.R; text.docx is the data). 
[test.docx](https://github.com/wbelzak/regDIF/files/8404762/test.docx)
[test.txt](https://github.com/wbelzak/regDIF/files/8404764/test.txt)

The results show that the mirt can well obtain the estimates, but the regDIF yielded
`mean.cov1 = 0.5251`, `var.cov1 = -0.0602`, `X1.int. = 0.4376`, and other intercepts were around 0.5. 
1) It seems the regDIF cannot identify the focal-group mean and item intercepts. 
2) What does it mean by `var.cov1 = -0.0602`?

Regards,
CW

**Comment by wbelzak** [comment]
Hi CW,

regDIF standardizes the predictor data by default (i.e., standardizing predictor data is recommended for regularization.) If you include `stdz=F`, you should get nearly identical results with mirt. I did this and got the following impact effects:


```
fit <- regDIF(item.data = res, pred.data = gender, stdz = F,
              ,item.type="2pl", num.tau = 5,control=list(tol=1e-7)
              ,anchor=1:itemnum,tau=0)
fit$impact
```
> mean.cov1  1.0203
> var.cov1  -0.1208

`var.cov1` is the effect of the DIF predictor on the latent variance. So, `var.cov1 = -0.1208` means that the female group has a variance of .88 (given the default variance of the reference group is 1, i.e., 1 - 0.1208 = .88). 

I hope that helps.

Best,
Will
